## Thsi is NodePort svc
apiVersion: v1
kind: Service
metadata:
  name: my-public-svc
spec:
  type: NodePort
  selector:
    env: prod
    auth: ps
  ports:
    - targetPort: 80
      port: 2345
      nodePort: 30001
