## Secret is used by using valueFrom keyword & give secretKeyRef --> name and key 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: db
      team: backend
  template:
    metadata:
      labels:
        app: db
        team: backend
    spec:
      containers:
        - name: "mysql-container"
          image: "mysql:latest"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pratik-secret
                  key: "p"                  # key put in ""
            - name: MYSQL_DATABASE
              value: "psdb"             # value put in ""
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pratik-secret
                  key: "u"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pratik-secret
                  key: "p"
