apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    team: prod
  template:
    metadata:
      labels:
        app: web
        team: prod
    spec:
      containers:
        - name: "myrc-container"
          image: "pratikshinde55/apache-webserver"
